name: "Commit Check on PR"
on:
  pull_request:

permissions:
  pull-requests: write
  contents: read

jobs:
  check_commits:
    uses: forquare/reusable-workflows/.github/workflows/pr-commit-check.yaml@main

