name: Release on main

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  get_bump_type:
    if: github.ref == 'refs/heads/main' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      bump_type: ${{ steps.get_bump_type.outputs.bump_type }}
    steps:
    - id: get_bump_type
      run: |
        BUMP_TYPE=$(gh pr view ${{ github.event.pull_request.number }} --json labels | jq -r '.labels[].name' | grep '[-]bump' | sed 's/-bump$//' | sort | uniq | head -n 1)
        
        echo "bump_type=${BUMP_TYPE}"
        echo "bump_type=${BUMP_TYPE}" >> $GITHUB_OUTPUT

  release:
    needs: get_bump_type
    uses: forquare/reusable-workflows/.github/workflows/release-with-goreleaser.yaml@main
    with:
      release_type: ${{ needs.get_bump_type.outputs.bump_type }}
