name: Check PR commits with commitlint

on:
  workflow_call:

permissions:
  pull-requests: write

jobs:
  commitlint:
    container:
      image: commitlint/commitlint:19.5.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure commitlint
        run: |
          cat <<EOF > /tmp/commitlint.config.js
          const Configuration = {
              extends: ['@commitlint/config-conventional'],
              rules: {
                  'type-enum': [
                      2,
                      'always',
                      [
                          'build',
                          'chore',
                          'ci',
                          'docs',
                          'feat',
                          'fix',
                          'perf',
                          'refactor',
                          'revert',
                          'style',
                          'test',
                      ],
                  ],
                  'header-case': [0, 'never'],
                  'subject-case': [0, 'never'],
                  'body-case': [0, 'never'],
                  'scope-case': [0, 'never'],
                  'type-case': [0, 'never'],
              },
          };
          module.exports = Configuration;
          EOF

      - name: Validate PR commits with commitlint
        id: lint_commits
        run: |
          set -x
          git config --global --add safe.directory '*'
          OUTPUT=$(npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --config /tmp/commitlint.config.js 2>&1 || true)
          if [ -n "$OUTPUT" ]; then
              echo "$OUTPUT"
              # Print OUTPUT to stage output:
              EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
              echo "message<<$EOF" >> $GITHUB_OUTPUT
              echo "$OUTPUT" >> $GITHUB_OUTPUT
              echo "$EOF" >> $GITHUB_OUTPUT
              exit 1
          fi

      - uses: marocchino/sticky-pull-request-comment@v2.9.0
        if: always() && (steps.lint_commits.outputs.message != null)
        with:
          header: pr-commit-lint-error
          message: |
            Thank you for opening this pull request!

            We require all commits to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like one or more of your commits need to be adjusted.

            Each commit should follow the format:

            ```
            build(#8): Add release process
            ^      ^           ^
            |      |           |__ Subject
            |      |_______ Scope optional
            |____________ Type
            ```

            Valid types are defined in the [Conventional Commit Types](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) specification:

            - build
            - chore
            - ci
            - docs
            - feat
            - fix
            - perf
            - refactor
            - revert
            - style
            - test

            All scopes are valid, and not required.

            Details:

            ```
            ${{ steps.lint_commits.outputs.message }}
            ```

      # Delete a previous comment when the issue has been resolved
      - if: ${{ steps.lint_commits.outputs.message == null }}
        uses: marocchino/sticky-pull-request-comment@v2.9.0
        with:
          header: pr-commit-lint-error
          delete: true
