name: Check PR commits with commitlint

on:
  workflow_call:

jobs:
  commitlint:
    container:
      image: commitlint/commitlint:19.5.0
    runs-on: ubuntu-latest
    steps:
      - run: touch ~/.gitconfig

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      #- name: Configure commitlint
      #  run: |
      #    cat <<EOF > commitlint.config.js
      #    const Configuration = {
      #        extends: ['@commitlint/config-conventional'],
      #        rules: {
      #          'type-enum': [
      #            2,
      #            'always',
      #            [
      #              'build',
      #              'chore',
      #              'ci',
      #              'docs',
      #              'feat',
      #              'fix',
      #              'perf',
      #              'refactor',
      #              'revert',
      #              'style',
      #              'test',
      #            ],
      #          ],
      #        },
      #    };
      #    module.exports = Configuration;
      #    EOF
      #    cat commitlint.config.js

      - name: Validate PR commits with commitlint
        run: |
          git -C /__w/test-workflows/test-workflows config --list
          git config --global --list
          echo '------------------/\/\/\/\/\/\/\/\/\/\------------------'
          npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose --config commitlint.config.js
