name: Release with Go Releaser

on:
  workflow_call:
    inputs:
      release_type:
        description: 'The type of release to create, e.g., "patch", "minor", "major", or a specific tag name.'
        required: true
        type: string

jobs:
  check_files:
    runs-on: ubuntu-latest
    outputs:
      skip_release: ${{ steps.check.outputs.skip_release }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: 'Check for files_that_skip_release'
        run: |
          if [ ! -f .github/files_that_skip_release ]; then
            echo "File .github/files_that_skip_release does not exist. Skipping check."
            echo "skip_release=false" >> $GITHUB_OUTPUT
            exit 0
          fi

      - name: 'Get changed files'
        id: 'get_files'
        uses: masesgroup/retrieve-changed-files@491e80760c0e28d36ca6240a27b1ccb8e1402c13  # v3.0.0

      - name: 'Checking files'
        id: 'check'
        run: |
          echo "Skipping release - default"
          echo "skip_release=true" >> $GITHUB_OUTPUT

          if echo ${{ steps.get_files.outputs.all }} | tr ' ' '\n' | grep -Ev $(grep -Ev '^#|^$' .github/files_that_skip_release | tr '\n' '|' | sed 's/|$//'); then
            echo "Not skipping release"
            echo "skip_release=false" >> $GITHUB_OUTPUT
          fi

  tag:
    needs: check_files
    if: needs.check_files.outputs.skip_release == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b  # v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          default_bump: ${{ inputs.release_type }}

  build_and_release:
    needs: tag
    if: needs.check_files.outputs.skip_release == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # 5.5.0
        with:
          go-version: '^1.24'
          cache: false

      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552  # v6.3.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
